version: "3"
services:
  elasticsearch:
    image: elasticsearch:8.15.1
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      http.cors.enabled: "true"
      http.cors.allow-origin: "/.*/"
      http.cors.allow-headers: "X-Requested-With,Content-Length,Content-Type,Authorization"
      discovery.type: single-node
      xpack.security.enabled: "false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/esdatadir:/usr/share/elasticsearch/data
  kibana:
    image: kibana:8.15.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  logstash:
    image: dcm4che/logstash-dcm4chee:8.15.1-17
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "12201:12201/udp"
      - "8514:8514/udp"
      - "8514:8514"
      - "6514:6514"
      - "25826:25826/udp"
      - "9600:9600"
    depends_on:
      - elasticsearch
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/logstash:/usr/share/logstash/data
